[package]
name = "python-config"
version = "0.1.0"
authors = ["Ian McIntyre <ianpmcintyre@gmail.com>"]
edition = "2018"
description = """
Python distribution information
"""

[dependencies]
semver = "0.9"

[[bin]]
name = "python-config"
path = "src/main.rs"